### ISSUE TITLE
Create A database.

### ISSUE THREAD

**Issue by RealYusufIsmail** [Programming-Org/Programming#12]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Regarding the database system I will be using mariadb and jooq. Jooq will basically generate the database classes into java so they can be used with the bot. The database will be used to recorded bans, warns, kicks, etc. and will be use for the auto moderation system.

### Example Use-Case

```java
Null
```

**Comment by RealYusufIsmail** [comment]
@Haleloch What do you think.

**Comment by Haleloch** [comment]
> @Haleloch What do you think.

About jooq and mariadb ?

**Comment by RealYusufIsmail** [comment]
Yeah
