### ISSUE TITLE
Basic moderation commands

### ISSUE THREAD

**Issue by Haleloch** [Programming-Org/Programming#8]
### General Troubleshooting

- [X] I have checked for similar issues on the Issue-tracker.
- [X] I have checked the branches or the maintainers' PRs for upcoming features.

### Feature Request

Many commands for moderate users :

- [x] Ban/Unban
- [x] Tempban
- [x] Kick
- [x] TimeOut/Remove Timeout
- [x] Warn/remove warn
- [x] See list of infractions
- [x] Delete list of message of one user
- [x] Delete an amount of message in a channel

**Comment by Haleloch** [comment]
Obviously permissions must be checked

**Comment by RealYusufIsmail** [comment]
I will work on the kick, ban and unban command after I finish with the database system.
